### PR TITLE
Add Charter for Release SIG

### PR DESCRIPTION
**Pull request by zhiyingfang2022**
Hi~ I have added charter of release sig,please review it together.
cc @fisherxu @Shelley-BaoYue

### CODE REVIEW

**Review by fisherxu — COMMENTED** [review]
Please add a readme for the SIG, thanks

**Comment by zhiyingfang2022** [comment]
Thanks,Updated.
@fisherxu @Shelley-BaoYue

**Review by fujitatomoya — APPROVED** [review]
lgtm 👍 

i think most of the part comes from https://github.com/kubernetes/community/blob/master/sig-architecture/charter.md, but adjusted against the current KubeEdge SIGs.

**Review by fisherxu — COMMENTED** [review]
Please also add a README for sig-release :)

**Comment by zhiyingfang2022** [comment]
> Please also add a README for sig-release :)

ok,I'll sort it out later.

**Comment by zhiyingfang2022** [comment]
README for sig-release added.Please review. @fisherxu @Shelley-BaoYue

**Comment by zhiyingfang2022** [comment]
> lgtm 👍
> 
> i think most of the part comes from https://github.com/kubernetes/community/blob/master/sig-architecture/charter.md, but adjusted against the current KubeEdge SIGs.

Keen Eyes. 👍

**Comment by zhiyingfang2022** [comment]
Hi～The charter for the release SIG has been finalized. Please take another look. @kubeedge/maintainers @kubeedge/tsc

**Review by fisherxu — COMMENTED** [review]
/lgtm
Thanks for the great job.

**Pull request merged**
