### PR TITLE
Add the KubeEdge robotics SIG charter.

### PR DESCRIPTION
**Pull request by crystaldust**
Hi, dear community!

Based on what we have discussed before, we initiate to found the KubeEdge robotics SIG. Please help check the content and see if there is anything we need any further discussion.

### CODE REVIEW

**Comment by ugvddm** [comment]
Currently，two companies have joined our SIG, guyuehome and tianbot, and many other companies interested  and want to join us.

**Comment by huchunxu** [comment]
Hi, this is guyuehome. Thanks for founding the KubeEdge robotics SIG. It's very interesting. We will joint it and try to contribute.

**Review by fisherxu — COMMENTED** [review]
/lgtm

**Pull request merged**
