### PR TITLE
CNCF Governance Review: Updates for team security member

### PR DESCRIPTION
**Pull request by fisherxu**
Some updates for team security as discussed with TSC: 
1. Merge security owners to members, and they have the same responsibilities.
2. Add description for how security member get appointed and replaced, the appointment or replacement of members is recommended by existing members or the TSC, and is approved by a TSC vote finally.

### CODE REVIEW

**Comment by huanwei** [comment]
/lgtm
thanks

**Comment by kevin-wangzefeng** [comment]
We've get 6/7 pass from TSC members and @fisherxu as athor, this PR is ready to merge.

/hold cancel
/approve

**Pull request merged**
