### PR TITLE
add chairs for SIG device-iot

### PR DESCRIPTION
**Pull request by cl2017**
@fisherxu and @cl2017 have been contributed in SIG-Device-iot development for a long time, have also organized community SIG meetings, and will continue to work on the development of the SIG, so this PR will added them to SIG Chairs and Technical Leads

update-device-iot README.md

Signed-off-by: cl2017 <chenlin.liu@daocloud.io>

### CODE REVIEW

**Comment by tinatsou** [comment]
LGTM

**Comment by kevin-wangzefeng** [comment]
LGTM
Thanks

**Review by fisherxu — COMMENTED** [review]
/lgtm
Thanks for getting me involved @cl2017 , and +1 we will continue to work on the development of the SIG and to organize community SIG meetings :)

**Comment by HongbingZhang** [comment]
LGTM
Congratulation and good progress! Look forward to the upcoming big milestone

**Comment by kevin-wangzefeng** [comment]
We've got 6/7 approval from TSC members, thank you all for the support.
/approve

**Pull request merged**
